lsi: false
safe: true
source: mark-hurlstone/QJEP-Special-Issue-Pub
title: null
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
